[workspace]
authors = ["Moeary"]
channels = ["conda-forge"]
name = "CosyVoiceGUI"
platforms = ["win-64"]
version = "1.2.0"

[tasks]
start = "python main.py"
api = "python core/api.py --config config/小说.json --port 9880 --min_text_length 0"

[dependencies]
python = "3.12.*"
ffmpeg = "*"
modelscope = ">=1.33.0,<2"
flask = ">=3.1.2,<4"
flask_cors = ">=4.0.0,<5"

[pypi-dependencies]
torch = { url = "https://mirrors.aliyun.com/pytorch-wheels/cu128/torch-2.7.0%2Bcu128-cp312-cp312-win_amd64.whl" }
torchaudio = { url = "https://mirrors.aliyun.com/pytorch-wheels/cu128/torchaudio-2.7.0%2Bcu128-cp312-cp312-win_amd64.whl" }
torchvision = { url = "https://mirrors.aliyun.com/pytorch-wheels/cu128/torchvision-0.22.0%2Bcu128-cp312-cp312-win_amd64.whl" }
conformer = "==0.3.2"
diffusers = "==0.29.0"
fastapi = "==0.115.6"
fastapi-cli = "==0.0.4"
gdown = "==5.1.0"
hydra-core = "==1.3.2"
HyperPyYAML = "==1.2.2"
inflect = "==7.3.1"
librosa = "==0.10.2"
lightning = "==2.2.4"
matplotlib = "==3.7.5"
networkx = "==3.1"
omegaconf = "==2.3.0"
onnx = "==1.16.0"
onnxruntime = "==1.18.0"
openai-whisper = "==20231117"
protobuf = "==4.25"
pyarrow = "==18.1.0"
pydantic = "==2.7.0"
pyworld = "==0.3.4"
rich = "==13.7.1"
soundfile = "==0.12.1"
transformers = "==4.51.3"
uvicorn = "==0.30.0"
wetext = "==0.0.4"
wget = "==3.2"
grpcio = ">=1.76.0, <2"
grpcio-tools = ">=1.62.3, <2"
pyqt-fluent-widgets = ">=1.10.2, <2"
pyqt5 = ">=5.15.11, <6"
x_transformers = ">=1.0.0"
